name: build-database

on:
  workflow_call:

jobs:
    build-database:
        name: Build database
        runs-on: windows-latest
        steps:
        - uses: actions/checkout@v3
    
        - name: Prepare MSBuild
          uses: microsoft/setup-msbuild@v1.1
    
        - name: Build database project
          working-directory: ./src/wwi
          run: MSBuild.exe src/wwi/wwi.sqlproj -property:Configuration=Release
    
        - name: Upload website as workflow artifact
          uses: actions/upload-artifact@v3
          with:
            name: database
            path: ./src/wwi/bin/Release/wwi.ToyCompany.Database.dacpac