name: deploy-analytics-infrastructure
concurrency: hallinc-workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  
  # Lint the code.
  lint:
    uses: ./.github/workflows/lint.yml

  # Deploy to the test environment.
  deploy-to-test:
    uses: ./.github/workflows/deploy.yml
    needs: 
        - lint
    with:
      environmentType: Test
      resourceGroupName: hallinc-analytics-sandbox
      sqlServerAdministratorLogin: sqlServerAdmin
      parameterFile: './deploy/main.parameters.sandbox.bicepparam'

    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID_TEST }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      sqlServerAdministratorLoginPassword: ${{ secrets.SQL_SERVER_ADMINISTRATOR_LOGIN_PASSWORD_TEST }}

  # Deploy to the production environment.
  deploy-to-production:
      if: ${{ vars.DEPLOY_TO_PRODUCTION == true }}
      uses: ./.github/workflows/deploy.yml
      needs:
          - deploy-to-test
      with:
          environmentType: Production
          resourceGroupName: hallinc-analytics-production
          sqlServerAdministratorLogin: sqlServerAdmin
          parameterFile: './deploy/main.parameters.sandbox.bicepparam'
      secrets:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID_PRODUCTION }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          sqlServerAdministratorLoginPassword: ${{ secrets.SQL_SERVER_ADMINISTRATOR_LOGIN_PASSWORD_PRODUCTION }}
    